<?php

/**
 * @file
 * This is the Supersport development module.
 */

/**
 * Impements the hook_ajax_form_alter().
 */
function supersport_ajax_form_alter(&$form, &$form_state, $form_id) {

	switch($form_id) {
		case 'event_node_form':

			$lang = $form['field_sport']['#language'];
			$sport = $form['field_sport'][$lang]['#options'];

			$form['field_league']['#prefix'] = '<div id="league-options">';
			$form['field_league']['#suffix'] = '</div>';

			$form['field_teams']['#prefix'] = '<div id="teams-options">';
			$form['field_teams']['#suffix'] = '</div>';

			$form['field_sport'][$lang]['#ajax'] = array(
				'callback' => 'supersport_ajax_sportleague_callback',
				'wrapper' => 'league-options',
				'method' => 'replace',
				'effect' => 'fade',
			);

			$form['field_league'][$lang]['#ajax'] = array(
				'callback' => 'supersport_ajax_sportteams_callback',
				'wrapper' => 'teams-options',
				'method' => 'replace',
				'effect' => 'fade',
			);

			break;
	}
}

/**
 * Callback element needs only select the portion of the form to be updated.
 * Since #ajax['callback'] return can be HTML or a renderable array (or an
 * array of commands), we can just return a piece of the form.
 */
function supersport_ajax_sportleague_callback($form, $form_state) {
	$lang = $form['field_sport']['#language'];
	
	$field_sport_key = $form['field_sport'][$lang]['#value'];
	$field_sport = $form['field_sport'][$lang]['#options'][$field_sport_key];

	$vocabulary = taxonomy_vocabulary_machine_name_load('league');
	$terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));	

	$league_options = array();
	$league_options['_none'] = '- Select a value -';

	foreach ($terms as $key => $value) {

		if($value->field_sport[$lang][0]['tid'] == $field_sport_key) {

			$league_options[$key] = $value->name;
		}	
	}	

	$form['field_league'][$lang]['#options'] = $league_options;

	return $form['field_league'];
}

function supersport_ajax_sportteams_callback($form, $form_state) {
	$lang = $form['field_league']['#language'];

	$field_league_key = $form['field_league'][$lang]['#value'];
	$field_league = $form['field_league'][$lang]['#options'][$field_league_key];

	$vocabulary = taxonomy_vocabulary_machine_name_load('teams');
	$terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));	

	$team_options = array();
	$team_options['_none'] = '- Select a value -';

	foreach ($terms as $key => $value) {

		if($value->field_league[$lang][0]['tid'] == $field_league_key) {
			$team_options[$key] = $value->name;
		}	
	}	

	$form['field_teams'][$lang]['#options'] = $team_options;

	return $form['field_teams'];
}