<?php

/**
 * @file
 * Creates taxonomy breadcrumb to Supersport event nodes
 */

// Block constants
define('SS_BREADCRUMB', 'ss_breadcrumb');

// Remove breadcrumbs from all non specified pages
drupal_set_breadcrumb(array());

/**
 * Implements hook_block_info().
 */
function supersport_taxonomy_breadcrumb_block_info() {
  $blocks[SS_BREADCRUMB] = array(
    'info' => t('Supersport Taxonomy Breadcrumb'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function supersport_taxonomy_breadcrumb_block_view($delta = '') {
  $block = array();

  switch($delta) {
    case SS_BREADCRUMB:
      $block['subject'] = NULL;
      $block['content'] = array(
        '#theme' => 'baker',
      );
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function supersport_taxonomy_breadcrumb_theme() {
  return array(
    'baker' => array(
      'variables' => menu_get_item(),
    ),
  );
}

/**
 * Theme hook for breadcrumbs
 */
function theme_baker($variables) {
  //dpm($variables);

  // TODO
  // $type = node
  $node = menu_get_object();

  return '<h3 style="color:white">Theme function called</h3>';
}

/**
 * Implements hook_taxonomy_term_view_alter().
 */
function supersport_taxonomy_breadcrumb_taxonomy_term_view_alter($build) {

  // Get tid from current taxonomy term on display
  $tid = $build['#term']->tid;

  $crumbs = _build_trail($tid);
  drupal_set_breadcrumb($crumbs);
}

/**
 * Implements hook_node_view_alter().
 */
function supersport_taxonomy_breadcrumb_node_view_alter(&$build) {

  dpm($build);
}

/**
 * Builds breadcrumb trail based on taxonomy vocabularies
 * Trail: Sport > League > Team
 *
 * @param $tid_current
 *  Taxonomy term ID if the currently viewed node
 * @return array
 *  Array of breadcrumbs
 */
function _build_trail($tid_current) {
  $term_current = taxonomy_term_load($tid_current);

  // Parse member taxonomy terms
  $term_league = _term_parse($term_current, 'field_league');
  $term_sport = _term_parse($term_current, 'field_sport');

  // Fill breadcrumb
  $crumbs = array();

  _add_to_trail($term_sport, $crumbs);
  _add_to_trail($term_league, $crumbs);
  $crumbs[] = drupal_get_title();

  return $crumbs;
}

/**
 * Creates term array of member taxonomy term
 *
 * @param $term_object
 *  Taxonomy term object by taxonomy_load_term()
 * @param $field_name
 *  Field name of member taxonomy term
 * @return array
 *  If member field exists
 *    Term array with tid, object, path
 *  Else NULL
 */
function _term_parse($term_object, $field_name) {
  // Checks if member field exists
  if (!isset($term_object->$field_name)) {
    // If not, return NULL
    return NULL;
  }

  // Parse field tid from term
  $item = field_get_items('taxonomy_term', $term_object, $field_name);

  $tid = $item[0]['tid'];
  $object = taxonomy_term_load($tid);
  $path = taxonomy_term_uri($object)['path'];

  $term = array(
    'tid' => $tid,
    'object' => $object,
    'path' => $path,
  );

  return $term;
}

/**
 * Fills breadcrumb trails with member/parent fields
 *
 * @param $term_array
 *  Term array to be inserted into breadcrumb
 *  Created by _term_parse()
 * @param $crumbs
 *  Reference to crumbs to be inserted into breadcrumbs
 */
function _add_to_trail($term_array, &$crumbs) {
  // Term array exists
  if (isset($term_array)) {
    $crumbs[] = l(
      t($term_array['object']->name),
      $term_array['path']
    );
  }
}